# Jellyfin • AniLiberty STRM  – ция для JPRM
# (build.yaml должен лежать рядом с .csproj)

category: "Metadata"

artifacts: # DLL-ы, которые попадут в ZIP
  - "AniLibertyStrmPlugin.dll"
  - "Polly.dll"
  - "Polly.Core.dll"
  - "Polly.Extensions.Http.dll"
  - "Microsoft.Extensions.Http.Polly.dll"
  - "icon.png"

changelog: |
  • See GitHub Release notes for details


description: >
  Creates .strm / .edl / .nfo files for AniLiberty titles and favourites.

guid: "cce0798d-c8b7-4265-b08c-dc9e7bd3fc0f"
name: "AniLiberty STRM Plugin"
overview: >
  Generates STRM libraries for the full catalogue and/or user favourites,
  with EDL intro-skip and proper NFO metadata.
owner: "queukat"

targetAbi: "10.11.0.0"

version: "dev"


image: Resources/icon.png
